### PR TITLE
Add the cloudwatch mock functionality into the Aws-mock

### PR DESCRIPTION
**Pull request by Davinder2me**
Hi, 
Please review my pull request. This is about CloudWatch mock.

1.  Add the functionality to GetMetricStatistics API of Cloudwtach to mock.

2. Added the all required tests.

3. cxf-stub-1.0.2.jar has to uploaded to mvn repository.  

Thanks
Davinder

### CODE REVIEW

**Comment by maxiaohao** [comment]
This is an awesome pr - much appreciated!  When we started to develop aws-mock a couple of years ago we knew someday someone may add a mock other than EC2 and now you have done that!
Could you please also add the following: 
- 1. Update the wiki page "Technical Specs" (https://github.com/treelogic-swe/aws-mock/wiki/Technical-Specifications)
- 2. For now I find the coverage check failed due to lacking of sufficient test: 
```
project failed coverage check. Branch coverage rate of 60.6% is below 80.0%
project failed coverage check. Line coverage rate of 79.1% is below 80.0%
```
So you need to improve the coverage of your code by enhancing the unit tests and meet at least 80% coverage as defined in build.gradle. Running `gradle coberturaCheck check` would tell you if the coverage threshold is met, and a detailed report could be found in `build/cobertura`. 
- 3. Last but not least, please fix those minor issues in code per my rough code review in comments above. 

Sorry that I am too busy to put a hand into the work above for you. 
After you've done those with the pr updated, I will then merge your perfect work into aws-mock!

Thanks!

**Comment by Davinder2me** [comment]
I have updated the unit test and read me document. I will update the Technical specifications once you merged with master.

**Comment by Davinder2me** [comment]
Fix code with review comments. Please review.

**Comment by nottoseethesun** [comment]
Congrats @Davinder2me , awesome work!

**Comment by maxiaohao** [comment]
And I've also tagged and released the new version (v1.1.1).

**Comment by Davinder2me** [comment]
Thank you all.

**Pull request merged**
