### PR TITLE
Add SubnetSet CiDR Block

### PR DESCRIPTION
**Pull request by Davinder2me**
Hi,

Very minor changes. Please merge.

Thanks
Davinder

### CODE REVIEW

**Comment by Davinder2me** [comment]
Please merge to master.

**Comment by nottoseethesun** [comment]
We'll get to this soon.

**Comment by zakimak9** [comment]
Davinder2me,

The change to set CIDR block has been added. 

Thanks

**Comment by maxiaohao** [comment]
Thanks zakimak9 for merging Davinder2me's great code!

**Pull request merged**
